stages:
- name: Build--api server image
  steps:
  - publishImageConfig:
      dockerfilePath: ./app/Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/api-test:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.20.0.73:5443
    env:
      PLUGIN_INSECURE: "true"
      PLUGIN_MTU: "1000"
      PLUGIN_BUILD_ARGS: "--progress=tty --network=host"
      PLUGIN_MIRROR: "https://10.20.0.73:5443"
      PLUGIN_DEBUG: "true"

# 部屬使用者應用(app)
- name: Deploy app-web
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-web
      version: 0.2.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        # 基礎pipeline參數
        git.url: ${CICD_GIT_URL}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
        git.repoName: ${CICD_GIT_REPO_NAME}
        # web參數設定
        web.type: flask
        # 10.50.1.63:5443/app/${CICD_GIT_REPO_NAME}-web
        web.image: 10.50.1.63:5443/${CICD_GIT_REPO_NAME}/web
        web.tag: latest
        checkmarx.enabled: true
        #checkmarx.version: "0.9.2"
        checkmarx.version: "latest"
        newman.enabled: true
        apieditor.enabled: false
        codeServer.enabled: true
        codeServer.PASSWORD: happybear

#- name: Run webinspect-runner
#  steps:
#  - runScriptConfig:
#      image: iiiorg/webinspect-runner
#      shellScript: cd /usr/src/app; node /usr/src/app/app.js
#    env:
#      inspect_url: http://apitest.p-fppvh.10.20.0.80.xip.io/serverinfo
#      project_name: ${CICD_GIT_REPO_NAME}
#      git_branch: ${CICD_GIT_BRANCH}
#      git_commit_id: ${CICD_GIT_COMMIT}
#      verbose: true
#    envFrom:
#    - sourceName: webinspect
#      sourceKey: wi_base_url
#      targetKey: wi_base_url
#    - sourceName: api-origin
#      sourceKey: username
#      targetKey: api_username
#    - sourceName: api-origin
#      sourceKey: password
#      targetKey: api_password
#    - sourceName: api-origin
#      sourceKey: api-origin
#      targetKey: api_origin
notification: {}
