stages:
- name: Build--api server image
  steps:
  - publishImageConfig:
      dockerfilePath: ./app/Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: 10.20.0.73:5443
    env:
      PLUGIN_INSECURE: "true"
      PLUGIN_MTU: "1000"
      PLUGIN_BUILD_ARGS: "--progress=tty --network=host"
      PLUGIN_MIRROR: "https://10.20.0.73:5443"
      PLUGIN_DEBUG: "true"

